// shared/constants/roomTypes.ts
export const ROOM_TYPES = [
  'Bathroom',
  'Bedroom',
  'Kitchen',
  'Living Room',
  'Dining Room',
  'Office',
  'Laundry Room',
  'Garage',
  'Basement',
  'Attic',
  'Closet',
  'Pantry',
  'Mudroom',
  'Entryway',
  'Sunroom',
  'Home Gym',
  'Playroom',
  'Nursery',
  'Library / Study',
  'Workshop',
  'Theater / Media Room',
  'Guest Room',
  'Other',
];

export const ROOM_TYPE_ICONS: Record<string, string> = {
  Kitchen: '🍳',
  Bathroom: '🛁',
  Bedroom: '🛏️',
  'Living Room': '🛋️',
  'Dining Room': '🍽️',
  Office: '💻',
  'Laundry Room': '🧺',
  Garage: '🚗',
  Basement: '🏚️',
  Attic: '🪜',
  Closet: '🚪',
  Pantry: '🧂',
  Mudroom: '🥾',
  Entryway: '🚪',
  Sunroom: '🌞',
  'Home Gym': '🏋️',
  Playroom: '🎲',
  Nursery: '👶',
  'Library / Study': '📚',
  Workshop: '🔧',
  'Theater / Media Room': '🎬',
  'Guest Room': '🛎️',
  Other: '❓',
};
