// src/shared/houseRoomTemplates.ts
export const houseRoomTemplates: Record<string, { name: string; type: string; floor?: number }[]> = {
    Colonial: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Guest Room', type: 'Guest Room' },
      { name: 'Office', type: 'Office' },
    ],
    Ranch: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Laundry Room', type: 'Laundry Room' },
    ],
    Cape: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Bedroom 1', type: 'Bedroom' },
      { name: 'Bedroom 2', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Victorian: [
      { name: 'Parlor', type: 'Living Room' },
      { name: 'Formal Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Library', type: 'Office' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Craftsman: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Study', type: 'Office' },
    ],
    Modern: [
      { name: 'Great Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Home Office', type: 'Office' },
    ],
    Farmhouse: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Mudroom', type: 'Mudroom' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Guest Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Tudor: [
      { name: 'Great Hall', type: 'Living Room' },
      { name: 'Formal Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Library', type: 'Office' },
      { name: 'Master Suite', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Mediterranean: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Formal Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Courtyard', type: 'Mudroom' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    SplitLevel: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Family Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Guest Room', type: 'Guest Room' },
    ],
    Contemporary: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Home Office', type: 'Office' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Guest Room', type: 'Guest Room' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Cottage: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Sunroom', type: 'Sunroom' },
    ],
    LogCabin: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
      { name: 'Loft', type: 'Guest Room' },
    ],
    Townhouse: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Dining Room', type: 'Dining Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
    Bungalow: [
      { name: 'Living Room', type: 'Living Room' },
      { name: 'Kitchen', type: 'Kitchen' },
      { name: 'Primary Bedroom', type: 'Bedroom' },
      { name: 'Guest Room', type: 'Guest Room' },
      { name: 'Bathroom', type: 'Bathroom' },
    ],
  };
  